### ISSUE TITLE
fields.py

### ISSUE THREAD

**Issue by oditorium** [defrex/django-encrypted-fields#18]
I think in [fields.py](https://github.com/defrex/django-encrypted-fields/blob/master/encrypted_fields/fields.py) you want it to say

    self._crypter = keyczar.Crypter.Read(keyname)

otherwise this does not make sense

    def crypter(self):
        return self._crypter

**Comment by patientdev** [comment]
[`return self._crypter`](https://github.com/defrex/django-encrypted-fields/blob/master/encrypted_fields/fields.py#L154) really refers to [`self._crypter = self._crypter_klass(self.keydir)`](https://github.com/defrex/django-encrypted-fields/blob/master/encrypted_fields/fields.py#L139) which then refers to [`self._crypter_klass = kwargs.pop('crypter_klass', KeyczarWrapper)`](https://github.com/defrex/django-encrypted-fields/blob/master/encrypted_fields/fields.py#L97) which is what is referring to [`self.crypter = keyczar.Crypter.Read(keyname)`](https://github.com/defrex/django-encrypted-fields/blob/master/encrypted_fields/fields.py#L27)

**Going to try and explain that more clearly**: `return self._crypter` is returning a _crypter class_ that could be either a custom class given as a kwarg or defaulting to _KeyczarWrapper_. _KeyczarWrapper_ specifically defines its crypter as Google's _keyczar_ but a custom class could define its own crypter.

The _EncryptedFieldMixin_ takes whichever crypter it's given, whether custom or default, and assigns it as a ["private" instance variable](https://docs.python.org/3/tutorial/classes.html#tut-private), specifically `self._crypter_klass`. 

`self._crypter` is another private class variable that instantiates the assigned `self._crypter_klass` with a filesystem location (`self.keydir`) for the encryption key.

`def crypter(self)` simply returns the assigned `self._crypter`, seemingly to explicitly define the crypter syntatically with parentheses, reflecting that `self._crypter` is an instantiated object belonging to the mixin with its own methods, hence [`self.crypter().decrypt(value)`](https://github.com/defrex/django-encrypted-fields/blob/master/encrypted_fields/fields.py#L170)

All in all, this makes sense to me because `self.crypter` in _KeyczarWrapper_ is not a ["private" class variable](https://docs.python.org/3/tutorial/classes.html#tut-private) and therefore should not have an underscore. `self._crypter` in _EncryptedFieldMixin_ **should** have an underscore because it's only used within that class and is not intended to be used as an public attribute of the mixin.

> Note: I did not write any of the code under discussion. I have been job hunting and trying to explain helps keep me sharp for whatever might come up. Apologies for the verbosity. Happy to hear why I'm wrong, also.
